development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://:p4876df727b5470251ea3faa7122eb459736e49359f8eada465c7a2ed51afc2d8@ec2-54-158-253-251.compute-1.amazonaws.com:21109
  #channel_prefix: message_me_production
