development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://:pcabc61918b52e2ae4067cb8e029216cb2c9a52f01374dc779618dac1924ad11f@ec2-18-232-22-113.compute-1.amazonaws.com:7679
  #channel_prefix: message_me_production
